spring:
  application:
    name: aop-ltw
  datasource:
    url: jdbc:postgresql://localhost:5432/aop-ltw-tenant
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true